# -*- coding: utf-8 -*-
"""scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/130bHiWnubRMMB3kQsaP4uU6kcdtIWiZZ
"""

!pip install --quiet torch torchvision torchaudio tqdm

import os, json, time, random
from pathlib import Path
from tqdm.auto import tqdm

import torch
import torch.nn as nn
from torch.nn import functional as F

data_path = "synthetic_dataset.json"

with open(data_path, "r", encoding="utf-8") as f:
    data = json.load(f)

text = ""
for obj in data:
    orig = obj.get("original_text", "").strip()
    emo = obj.get("target_emotion", "").strip()
    targ = obj.get("transformed_text", "").strip()
    if orig and targ:
      text += f"Instruction: Rewrite the following text in a {emo} tone.\nOriginal: {orig}\nRewritten: {targ}\n\n"

Simport torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 128 #32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 128 #64
n_head = 8   # instead of 4
n_layer = 6  # instead of 4
dropout = 0.1 # instead of 0.0


torch.manual_seed(1337)

data_path = "synthetic_dataset.json"

with open(data_path, "r", encoding="utf-8") as f:
    data = json.load(f)

# Convert each example to a single string with special tags
# Convert each example to a prompt-style string
texts = []
for sample in data:
    orig = sample.get("original_text", "").strip()
    emo = sample.get("target_emotion", "").strip()
    targ = sample.get("transformed_text", "").strip()
    if orig and targ:
        texts.append(
            f"Instruction: Rewrite the following text in a {emo} tone.\n"
            f"Original: {orig}\n"
            f"Rewritten: {targ}\n\n"
        )



# Combine everything into one long string for training
full_text = "".join(texts)

# all the unique characters in text
chars = sorted(list(set(full_text)))
vocab_size = len(chars)
# mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data_tensor = torch.tensor(encode(full_text), dtype=torch.long)
n = int(0.9*len(data_tensor)) # first 90% will be train, rest val
train_data = data_tensor[:n]
val_data = data_tensor[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)
        q = self.query(x)
        wei = q @ k.transpose(-2,-1) * C**-0.5
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf'))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x)
        out = wei @ v
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        tok_emb = self.token_embedding_table(idx)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device))
        x = tok_emb + pos_emb
        x = self.blocks(x)
        x = self.ln_f(x)
        logits = self.lm_head(x)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :]
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Recreate your character mappings from training
chars = sorted(list(set(full_text)))
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

# Function to generate text with temperature
def generate_with_temperature(model, context, max_new_tokens=400, temperature=0.7):
    idx = context
    for _ in range(max_new_tokens):
        # crop to block_size
        idx_cond = idx[:, -block_size:]
        logits, _ = model(idx_cond)
        logits = logits[:, -1, :] / temperature
        probs = torch.softmax(logits, dim=-1)
        idx_next = torch.multinomial(probs, num_samples=1)
        idx = torch.cat((idx, idx_next), dim=1)
        # Stop if double newline occurs (end of sentence in our dataset)
        generated_text = decode(idx[0].tolist())
        if "\n\n" in generated_text:
            break
    return idx

# Function to rewrite a sentence in a target emotion
def rewrite_sentence(model, original_sentence, target_emotion):
    prompt = f"Instruction: Rewrite the following text in a {target_emotion} tone.\nOriginal: {original_sentence}\nRewritten:"
    context = torch.tensor([encode(prompt)], dtype=torch.long, device=device)

    generated_tensor = generate_with_temperature(model, context, max_new_tokens=400, temperature=0.7)
    generated_text = decode(generated_tensor[0].tolist())

    # Extract only the rewritten part (stop at first newline or double newline)
    if "Rewritten:" in generated_text:
        rewritten = generated_text.split("Rewritten:")[1].split("\n")[0].strip()
    else:
        rewritten = generated_text.strip()

    # Print in clean format
    print(f"original: {original_sentence}")
    print(f"emotion: {target_emotion}")
    print(f"rewritten: {rewritten}\n")

# Examples
rewrite_sentence(m, "A person walked down the street carrying a box.", "tense")
rewrite_sentence(m, "I woke up early and opened the window to see the garden.", "joyful")
rewrite_sentence(m, "The person ran in the middle of the night.", "scary")
rewrite_sentence(m, "The waiter brought the wrong order for the second time.", "romantic")

# Challenging Examples
rewrite_sentence(m, "The children were eating ice cream in the park. The sun was shining brightly and birds were singing.", "tense")
rewrite_sentence(m, "Hello.", "melancholic")